using System;
using SQLite;

namespace NATAB
{
	public class tbl_Users
	{
		[PrimaryKey, AutoIncrement]
		public int UserId { get; set; }

		public int LocationId { get; set; }
		public string UserName { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string FullName { get; set; }
		public string Password { get; set; }
		public int Age { get; set; }
		public int Gendre { get; set; } //0 = Férfi, 1 = Nő
		public string UserTypeIds { get; set; }
		public int NationalityId { get; set; }
		public string RegDate { get; set; }
		    
		public tbl_Users()
		{
		}

		//PrimaryKey - This property is the primary key of the table.Only single-column primary keys are supported.
		//AutoIncrement - This property is automatically generated by the database upon insert.
		//Indexed - This property should have an index created for it.
		//MaxLength - If this property is a String then MaxLength is used to specify the varchar max size.The default max length is 140.
		//Ignore - This property will not be in the table.
	}
}
